import type { NextPage } from 'next'
import Head from 'next/head'
import React from "react";
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>HOME | SimpleBee </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to FreemanBees!
        </h1>

        <p className={styles.description}>
          A Bee &amp; Honey Business.
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>CardPlaceHolder1 &rarr;</h2>
            <p>CardPlaceHolder1 text</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>CardPlaceHolder2 &rarr;</h2>
            <p>CardPlaceHolder2 text</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a> footer placeholder </a>
      </footer>
    </div>
  )
}

export default Home
